# Generated by Django 5.1.7 on 2025-04-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_bid_id_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='closing_date',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
