# Generated by Django 5.1.7 on 2025-04-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bid_closing_date_bid_bidder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('id', 'price')},
        ),
    ]
