# Generated by Django 5.1.7 on 2025-04-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_bider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bider',
            new_name='bidder_id',
        ),
    ]
