# Generated by Django 5.1.7 on 2025-05-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_auction_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
