# Generated by Django 5.1.7 on 2025-05-14 13:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auction_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Número de tarjeta (13–19 dígitos)', max_length=19, validators=[django.core.validators.RegexValidator(message='El número de tarjeta debe contener solo dígitos y tener entre 13 y 19 caracteres', regex='^\\d{13,19}$')])),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Saldo disponible en el monedero', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
